#+TITLE: Redoing ML exercises in CL

Some time ago, I took a course on ML with examples in
Octave/Matlab. This repository tries to redo the stuff in Common Lisp.

* Linear algebra
I need linear combinations and matrix (including
   row and column vector) multiplication. I met quite a few LA
   libraries, some native, some using FFI, and most of them is a bit
   too complicated. Also, I wanted to get a feeling on speed of simple
   code.

** Speed test
   :PROPERTIES:
   :ORDERED:  t
   :END:
This is speed test with current machine (HP notebook), sbcl,
 and safety level in the code 2

#+NAME: speed-test
#+header: :var rows=500 :var across=500
#+BEGIN_SRC lisp :package linear-algebra :var type="SINGLE-FLOAT" :var cols=500
  (let ((a (make-array `(,rows ,across) :element-type type
					:initial-element 0s0))
	(b (make-array `(,across cols) :element-type type
				       :initial-element 0s0)))
  
     (time-in-ms-as-real (times a b)))
#+END_SRC

The speeds for individual table types and sizes are like this on my machine:
#+NOTE: Use C-c* to recalculate
#+TBLNAME:
| rows | across | cols | element-type | time (ms) | per-ms |
|------+--------+------+--------------+-----------+--------|
|  500 |    500 |  500 | single-float |     391.0 | 319693 |
|------+--------+------+--------------+-----------+--------|
|  100 |    100 |  100 | single-float |       5.0 | 200000 |
|  200 |    200 |  200 | single-float |      30.0 | 266667 |
|  400 |    400 |   10 | single-float |       7.0 | 228571 |
|  400 |    400 |   20 | single-float |      14.0 | 228571 |
|  400 |    400 |   40 | single-float |      25.0 | 256000 |
|  400 |    400 |  100 | single-float |      58.0 | 275862 |
|  400 |    400 |  200 | single-float |     117.0 | 273504 |
|  400 |    400 |  400 | single-float |     236.0 | 271186 |
|  400 |    400 | 1000 | single-float |     600.0 | 266667 |
|  400 |    400 | 2000 | single-float |    1193.0 | 268231 |
|------+--------+------+--------------+-----------+--------|
|  400 |    400 |   50 | t            |     222.0 |  36036 |
#+TBLFM: $5='(org-sbe speed-test (type '$4) (cols $3) (rows $1) (across $2))::$6=round($1*$2*$3/$5)

It appears to provide relatively stable number of (rows*cols*across)
field in the tested ranges for floats.

* Linear regression in one variable

This is exercise 1 of the course. Gradient descent method is used to
minimise error function for linear regression of data in file
=ex1data1.txt= that is part of the exercise and can be found on-line.

This lisp source block generates coefficients =k= and =q= for best fit.
#+NAME: ex1-lr
#+BEGIN_SRC lisp :package regression :var file="~/src/machine-learning-course/ex1/ex1data1.txt"
(multiple-value-call #'linear-get-coefficients (read-comma-file file))
#+END_SRC

#+RESULTS: ex1-lr
| -3.8957806 | 1.1930337 |

The coefficients are used by the gnuplot to draw the line agains data points.
#+header: :var file="~/src/machine-learning-course/ex1/ex1data1.txt"
#+header: :var q=ex1-lr[0,0] :var k=ex1-lr[1,0]
#+BEGIN_SRC gnuplot :exports code :file ex1data1.svg :exports both
set xlabel "Population (in 10 000)"
set ylabel "Profit (in 10 000 USD)"
set key box linestyle -1 left top
plot file using "%lf,%lf\n" title "Training data",\
   q+k*x title "Linear regression"
#+END_SRC

#+RESULTS:
[[file:ex1data1.svg]]

* Multiple variable LR
Actually, original point of the second part of example 1 was to
introduce normalization of the data set. This was not done so far.

#+NAME: ex1data2
#+BEGIN_SRC lisp :package regression :var file="~/src/machine-learning-course/ex1/ex1data2.txt"
  (multiple-value-call #'linear-get-coefficients
   (read-comma-file file) :sigma -1.25e-2)
#+END_SRC

#+RESULTS: ex1data2
| 89597.81 | 139.21062 | -8737.958 |

The coefficients are used by the gnuplot to draw the line agains data points.
#+header: :var file="~/src/machine-learning-course/ex1/ex1data2.txt"
#+header: :var q=ex1data2[0,0] :var k1=ex1data2[1,0] :var k2=ex1data2[2,0]
#+BEGIN_SRC gnuplot :exports code :file ex1data2.svg :exports both
set xlabel "Size"
set ylabel "Rooms"
set zlabel "Cost"
set view 110,15
set key box linestyle -1 left top
splot file using "%lf,%lf,%lf\n" title "Training data",\
   q+k1*x+k2*y title "Linear regression"
#+END_SRC

#+RESULTS:
[[file:ex1data2.svg]]

* Logistic
#+NAME: ex2data1
#+BEGIN_SRC lisp :package regression :var file="~/src/machine-learning-course/ex2/ex2data1.txt"
(multiple-value-call #'logistic-get-coefficients (read-comma-file2 file) :sigma -1s0 :rho 0.9999)
#+END_SRC

#+RESULTS: ex2data1
| 62.191525 | -0.5268614 | 1.3495767 | -6334.4214 |

The coefficients are used by the gnuplot to draw the line agains data points.
#+header: :var file="~/src/machine-learning-course/ex2/ex2data1.txt"
#+header: :var q=ex2data1[0,0] :var k1=ex2data1[1,0] :var k2=ex2data1[2,0]
#+header: :var k3=ex2data1[3,0]
#+BEGIN_SRC gnuplot :exports code :file ex2data1.svg :exports both
set key box linestyle -1 right top
plot file using 1:($3 == 1 ? $2 : 1/0) "%lf,%lf,%lf\n" title "1",\
   file using 1:($3 == 0 ? $2 : 1/0) "%lf,%lf,%lf\n" title "0", \
   (-q-k1*x-k3/x)/k2
#+END_SRC

#+RESULTS:
[[file:ex2data1.svg]]

* Testing sigma values
#+header: :results table :exports both
#+BEGIN_SRC lisp :package regression :var file="~/src/machine-learning-course/ex2/ex2data1.txt"
  (multiple-value-call #'logistic-try-sigmas
    (read-comma-file2 file)
    -1s0 :count '(10 30 100 300 1000 3000)
    :alpha -0.001)
#+END_SRC

#+RESULTS:
|        -0.1 | 6.3692617 |  4.8979435 |  3.725777 | 2.5872898 | 1.6534188 | 1.1374117 |
| -0.31622776 | 4.7227216 |   3.717821 | 2.5447087 | 1.6654567 | 1.1283747 | 0.9603763 |
|        -1.0 | 4.5095177 |  2.2964587 | 2.1786563 |  1.651594 | 1.0812421 | 1.1020235 |
|  -3.1622777 | 11.805706 |  4.7092443 |  2.269913 |  4.750626 | 3.3716142 | 3.4681864 |
|       -10.0 |      12.0 | 11.9999895 |  9.114239 |  7.634916 | 2.7917109 |  2.617542 |

#+header: :results none
#+BEGIN_SRC lisp :package regression :var file="~/src/machine-learning-course/ex2/ex2data1.txt"
  (with-open-file (*standard-output* "/tmp/sigmas.txt"
				     :direction :output :if-exists :supersede)
    (princ "#")
    (apply #'map nil
	   (lambda (&rest data) (format t "~{~A~^ ~}~%" data))
	   (multiple-value-call #'logistic-try-sigmas
				    (read-comma-file2 file)
				    -1s0 :count (alexandria:iota 50 :step 60 :start 400)
				    :alpha -0.001)))
#+END_SRC

#+BEGIN_SRC gnuplot :exports code :file err.svg :exports both :var file="/tmp/sigmas.txt"
plot \
   file using 1 title "0" with lines, \
   file using 2 title "1" with lines, \
   file using 3 title "2" with lines, \
   file using 4 title "3" with lines
#+END_SRC

#+RESULTS:
[[file:err.svg]]


* BUGS/next steps
- [X] (check-logistic): parameter args added but not used
- [ ] Linear combination being destructive is counterintuitive. Rename
  to update and define true non-destructive combination
- [X] Normalization of X is missing
- [X] Better optimizer for logistic example <- fixed a bit by scaling
- [ ] Do not regularize A_0 (why?)
